version: '3'
services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
